/** This is going to be refactored resulting in removing these REST calls from this file */
/*  API CONSTANTS ENDPOINTS FOR CALENDAR WIDGET USING JSONplaceholder generated data. */
/*  resources: https://jsonplaceholder.typicode.com/ */

// export const FETCHPOSTS = (url) => { // contains user api data with nested objects that are autogenerated from JSON-server
//     url = 'https://jsonplaceholder.typicode.com/posts';
//     fetch(url)
//         .then(response => response.json())
//         .then(json => console.log(json));
//     // .then(json => alert(JSON.stringify(json))) can be used to show the data within an alert
// };
//
// export const FETCHCOMMENTS = (url) => { // contains user api data with nested objects that are autogenerated from JSON-server
//     url = 'https://jsonplaceholder.typicode.com/comments';
//     fetch(url)
//         .then(response => response.json())
//         .then(json => console.log(json));
//     // .then(json => alert(JSON.stringify(json))) can be used to show the data within an alert
// };
//
// export const FETCHALBUMS = (url) => { // contains user api data with nested objects that are autogenerated from JSON-server
//     url = 'https://jsonplaceholder.typicode.com/albums';
//     fetch(url)
//         .then(response => response.json())
//         .then(json => console.log(json));
//     // .then(json => alert(JSON.stringify(json))) can be used to show the data within an alert
// };
//
// export const FETCHPHOTOS = (url) => { // contains user api data with nested objects that are autogenerated from JSON-server
//     url = 'https://jsonplaceholder.typicode.com/photos';
//     fetch(url)
//         .then(response => response.json())
//         .then(json => console.log(json));
//     // .then(json => alert(JSON.stringify(json))) can be used to show the data within an alert
// };
//
// export const FETCHUSERS = (url) => { // contains user api data with nested objects that are autogenerated from JSON-server
//     url = 'https://jsonplaceholder.typicode.com/users';
//     fetch(url)
//         .then(response => response.json())
//         .then(data => this.setState({ data: data}))
//         .then(json => console.log(json));
//     // .then(json => alert(JSON.stringify(json))) can be used to show the data within an alert
// };
//
// export const FETCHTODOS = (url) => { // contains user api data with nested objects that are autogenerated from JSON-server
//     url = 'https://jsonplaceholder.typicode.com/todos';
//     fetch(url)
//         .then(response => response.json())
//         .then(json => console.log(json));
//     // .then(json => alert(JSON.stringify(json))) can be used to show the data within an alert
// };